PREFIX taco: <https://w3id.org/taco-rdf/vocab#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?source ?relation ?target ?review_status ?version_status ?version ?review_round ?reviewed_on
       (GROUP_CONCAT(DISTINCT COALESCE(?reviewer, ""); separator="; ") AS ?reviewers) ?rationale
WHERE {
  ?assertion a taco:AlignmentAssertion ;
      rdf:subject ?source ; rdf:predicate ?relation ; rdf:object ?target ;
      taco:reviewStatus ?review_status ; taco:ontologyVersionStatus ?version_status .
  OPTIONAL { ?assertion taco:ontologyVersion ?version }
  OPTIONAL { ?assertion prov:wasDerivedFrom ?review_round . ?review_round a taco:ReviewRound }
  OPTIONAL { ?assertion dcterms:date ?reviewed_on }
  OPTIONAL { ?assertion taco:reviewer ?reviewer }
  OPTIONAL { ?assertion skos:editorialNote ?rationale }
}
GROUP BY ?source ?relation ?target ?review_status ?version_status ?version ?review_round ?reviewed_on ?rationale
ORDER BY ?source ?relation ?target
