PREFIX taco:    <https://w3id.org/taco-rdf/vocab#>
PREFIX tacoid:  <https://w3id.org/taco-rdf/id/>
PREFIX nutrient: <https://w3id.org/taco-rdf/id/nutrient/>
PREFIX category: <https://w3id.org/taco-rdf/id/category/>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qudt:    <http://qudt.org/schema/qudt/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX prov:    <http://www.w3.org/ns/prov#>

SELECT ?food_label ?amino_acid ?value_g ?food_label_en
WHERE {
  ?m taco:ofFood ?food ;
     taco:ofNutrient ?n ;
     taco:valueStatus taco:Measured ;
     qudt:numericValue ?value_g .
  ?n skos:broader category:amino_acid ;
     skos:prefLabel ?amino_acid .
  ?food rdfs:label ?food_label .
  FILTER (LANG(?amino_acid) = "en")
  OPTIONAL { ?food skos:prefLabel ?food_label_en . FILTER (LANG(?food_label_en) = "en") }
}
ORDER BY DESC(?value_g)
