PREFIX taco:    <https://w3id.org/taco-rdf/vocab#>
PREFIX tacoid:  <https://w3id.org/taco-rdf/id/>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?food_number ?food ?relation ?foodon_class ?foodon_label ?food_en
WHERE {
  ?f a taco:Food ;
     taco:foodNumber ?food_number ;
     rdfs:label ?food ;
     ?rel ?target .
  ?target rdfs:label ?foodon_label .
  FILTER (LANG(?food) = "pt" && ?rel IN (rdf:type, skos:closeMatch, skos:narrowMatch, skos:broadMatch, skos:relatedMatch, skos:exactMatch))
  FILTER (STRSTARTS(STR(?target), "http://purl.obolibrary.org/obo/FOODON_"))
  BIND (IF(?rel = rdf:type, "type", STRAFTER(STR(?rel), "core#")) AS ?relation)
  BIND (STRAFTER(STR(?target), "obo/") AS ?foodon_class)
  OPTIONAL { ?f skos:prefLabel ?food_en . FILTER (LANG(?food_en) = "en") }
}
ORDER BY ?food_number
